language: go

go:
  - 1.0
  - 1.1

notifications:
  email: false

services:
  - redis

script: go test -v ./test

install:
  - go get -u github.com/adeven/redis
  - go get -u github.com/matttproud/gocheck
